const REGISTRATION = 'loft-taxi/registration/REGISTRATION';
const REGISTRATION_COMPLETED = 'loft-taxi/registration/REGISTRATION_COMPLETED';
const REGISTRATION_FAILED = 'loft-taxi/registration/REGISTRATION_FAILED';

export { REGISTRATION, REGISTRATION_COMPLETED, REGISTRATION_FAILED };
